require 'opal'
require 'javascript/vendor/jquery'
require 'javascript/vendor/jquery-ui.min'
require 'opal-jquery'
require 'opal-parser'
require 'browser'
require 'browser/interval'
require 'browser/delay'
require 'browser/location'
require 'javascript/vendor/modernizr-custom'
require 'bblib'
require 'javascript/vendor/datatables.min'
require 'javascript/vendor/dataTables.bootstrap4.min'
require 'javascript/vendor/alertify'
# require 'javascript/widgets/_widgets'
# require 'javascript/vendor/chart'
require 'javascript/vendor/fontawesome-all.min'
require 'javascript/vendor/select2.min'
require 'javascript/vendor/flatpickr.min'
require 'javascript/vendor/tether.min'
require 'javascript/vendor/baguetteBox.min'
require 'javascript/vendor/bootstrap.min'
# require 'javascript/vendor/turbolinks'
require 'javascript/vendor/extensions'
require 'javascript/vendor/lazyload.min'
require 'javascript/block_stack'
require 'dformed'
